version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    ports:
      - 9200:9200
      - 9300:9300 
    environment:
      - "discovery.type=single-node"
    restart: on-failure
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"